// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ozmxxalzogcwotxrdpuu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im96bXh4YWx6b2djd290eHJkcHV1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkyNzg1OTcsImV4cCI6MjA2NDg1NDU5N30.2S4nkrGZtfSmonp0TwjhnnztCgr_ajyjN2KcbszuzW4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);